### ISSUE TITLE
[🐛 Bug]: First Notebook Cell Execution Fails with Multiple Scope Errors

### ISSUE THREAD

**Issue by rrrodzilla** [wiseaidev/rust-data-analysis#18]
**👶 Getting Started**  
Please [search the history](https://github.com/wiseaidev/rust-data-analysis/issues) to see if an issue already exists for the same problem.

- [X] I have searched the existing issues.
- [X] I have tested the latest version.

**📝 Describe the bug**  
This project looks interesting but I'm unable to proceed past the first step in notebook 1 which is installing dependencies. Running the first cell in the Rust kernel results in 4 errors, each stating: "multiple applicable items in scope".

**🕹 Steps to reproduce**

1. Follow the install instructions from the README file.
2. Open and run the first notebook.
3. Switch to the Rust kernel.
4. Run the first cell in the notebook.
5. After about 45 seconds, the cell fails with errors.

**😯 Current behavior**  
The cell fails to complete and instead throws 4 errors indicating "multiple applicable items in scope". (See attached screenshot for more details)

**🤔 Expected behavior**  
The cell should complete its execution successfully and allow me to advance to the next notebook cell.

**📸 Screenshots**  
<img width="946" alt="image" src="https://github.com/wiseaidev/rust-data-analysis/assets/24578097/62d0acc5-6a09-4e30-946e-b67561c84a93">

**🔦 Additional context**  
I'm new to Rust-based data analysis (but not data analysis in general) and was really looking forward to going through the notebooks. This issue has currently halted my progress and I'm unable to move beyond the first notebook.

**Comment by wiseaidev** [comment]
Hi there, @rrrodzilla! I really appreciate you taking the time to report this issue. It looks like [the newer releases of `evcxr`](https://github.com/evcxr/evcxr/releases) have come up with a new feature – they now support those informative "Compiling" messages starting from version [`v0.15.0`](https://github.com/evcxr/evcxr/releases/tag/v0.15.0). From what I can gather, you must be using a version that's newer than `v0.15.0`. My last experience was with version [`v0.14.2`](https://github.com/evcxr/evcxr/releases/tag/v0.14.2).

As the output suggests, you might want to try breaking down your statements into separate cells and running each line as its own command. If no one gets around to addressing this issue by the weekend, I'm planning on diving into the latest version myself. Thanks again for raising this concern!
