### ISSUE TITLE
Do I need to install dependencies every time I run the notebook?

### ISSUE THREAD

**Issue by langslike** [wiseaidev/rust-data-analysis#41]
When I first run 3-polars-tutorial-part-1.ipynb, I already installed every dependencies, and the code runs fine. But when I open the notebook for the second time, it seems that I have to install dependencies again, and its time consuming.
when I try to skip the code that install polars:
:dep polars = { version = "0.35.0", features = ["describe", "lazy", "ndarray", "object", "dtype-struct", "concat_str", "mode"] }
I got error when running this code:
use polars::datatypes::DataType;
use polars::prelude::*;
use chrono::{DateTime, NaiveDateTime, TimeZone, Utc};
use std::sync::Arc;
The errors are:
[E0433] Error: failed to resolve: use of undeclared crate or module `polars`
[E0433] Error: failed to resolve: use of undeclared crate or module `polars`

How to use locally installed crates with rust notebook?

**Comment by wiseaidev** [comment]
Hello!

You can use the `:cache` command to enable and set the compilation cache. Have a look at [the updated tutorial 1](https://github.com/wiseaidev/rust-data-analysis/blob/main/1-iris-data-analysis-rust.ipynb).
